### ISSUE TITLE
[PE-D] Unable to calcuate group expenses

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-1/tp#331]
From the UG, it is expected that in a scenario where, in a group of 2 contacts, and 1 of the contact has an expense, the calculated payment will be that the other contact pays half of the expense to the first contact.

However, the app shows that `There are no payments to be made!`.

Test group and contacts:

<img src="https://raw.githubusercontent.com/JeffZincatz/ped/main/files/cd69f4b0-ee65-46e7-8f3c-78c7c43adfac.png" width=600“ >

Expenses of the group:

<img src="https://raw.githubusercontent.com/JeffZincatz/ped/main/files/d88990f3-a7a3-4518-a4ae-986f7cebc77e.png" width="800">

Result for `calculatepayments gn/Group1`:

<img src="https://raw.githubusercontent.com/JeffZincatz/ped/main/files/8a520d76-519e-4b77-aea3-1f0b7d12bd6f.png" width="800">

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: JeffZincatz/ped#8

**Comment by ramapriyan912001** [comment]
Hi, 
Thank you for the feedback!
Could you give me an idea of the order of commands you utilised?

I am assuming you created a fresh group with 2 members.
This group had no expenses.

You subsequently added an expense using the command 
`addexpense n/Test1 gn/Group1 $/SOME_AMOUNT d/testExpense`

Then you entered `calculatepayments gn/Group1` and found the message that no payments were to be made.
Expected behaviour was to show the message: "`Test4` pays $`SOME_AMOUNT/2` to `Test1`"

Is this an accurate description of your journey?
